#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Holberton School"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School!' > /var/www/html/index.html
service nginx start
