#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx restart
