#!/usr/bin/env bash
#Installing nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

sudo sed -i "/listen 80 default_server; error_page404 /error404.html; /a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
